
global:
  seed: 42 # Random seed for reproducibility
  device: auto # Device to run the training on, can be 'cpu' or 'cuda' or 'auto'

env:
  id: CartPole-v1
  

network:
  type: base # Type of agent, can be 'base', 'dueling','dueling_noise', etc.
  hidden_dim: 128 # Number of hidden units in the MLP
  optimizer: Adam # Optimizer to use for training， can be 'Adam', 'RMSprop', etc.

agent:
  type: base 
  gamma: 0.99
  buffer_size: 100000
  learning_starts: 1000
  target_update_interval: 100

explore_shedule:
  policy: exp
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay: 10000

train:
  record_video: True # Whether to record videos of the environment
  episodes: 10000 # Total number of episodes to train
  batch_size: 32
  lr: 0.0003
  save_path: ../checkpoints/dqn.pth # Path to save the trained model

eval:
  episodes: 10 # Number of episodes to evaluate the agent
  render: Human # Whether to render the environment during evaluation

logging:
  log_dir: ./logs/
  save_interval: 1000

